//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Database_using_ADO.net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dep_tbl
    {
        public int Dep_id { get; set; }
        public string Name { get; set; }
    }
}
