//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delete_record.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_tbl
    {
        public int Emp_ID { get; set; }
        public string Emp_name { get; set; }
        public Nullable<int> Dep_ID { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Department_tbl Department_tbl { get; set; }
    }
}
