//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cascading_dropdown.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class disease_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public disease_tbl()
        {
            this.Docter_tbl = new HashSet<Docter_tbl>();
        }
    
        public int des_ID { get; set; }
        public string des_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Docter_tbl> Docter_tbl { get; set; }
    }
}
